version: '3.9'
services:
  frontend:
    image: node:16.14-alpine

    working_dir: /front-app
    restart: on-failure

    stdin_open: true
    tty: true

    command: npm start

    ports:
      - 3000:3000
    depends_on:
      - backend

    volumes:
      - ./front-end:/front-app
     
  backend:
    image: node:16.14-alpine

    working_dir: /back-app
    restart: on-failure  

    stdin_open: true
    tty: true

    # command: npm start

    environment:
    - NODE_ENV=development
    - API_PORT=3001
    - HOSTNAME=db
    - MYSQL_PORT=3306
    - MYSQL_USER=root
    - MYSQL_PASSWORD=main4
    - MYSQL_DB_NAME=delivery-app
    - EVAL_ALWAYS_RESTORE_DEV_DB=true
    - JWT_SECRET='seusecretdetoken'

    ports: 
      - "3001:3001"

    depends_on:
      - db  

    volumes:
      - ./back-end:/back-app

  db:
    image: mysql:8.0.21

    restart: on-failure

    environment:
      - MYSQL_ROOT_PASSWORD=main4
      - MYSQL_DB_NAME=delivery-app

    ports:
      - 33006:3306

    