const typesError = {
  FAIL_CONNECT_DB: 500,
  USER_NOT_FOUND: 404,
  USERS_NOT_FOUND: 404,
  USER_NOT_CREATE: 500,
  USER_ALREADY_EXIST: 409,
  CATEGORIES_NOT_FOUND: 400,
  EXPIRED_OR_INVALID_TOKEN: 401,
  POST_NOT_CREATE: 500,
  POST_NOT_FOUND: 404,
};

module.exports = typesError;